# Generated by Django 5.2.4 on 2025-09-17 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_expense_date_alter_income_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='reimbursement',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
