# Generated by Django 5.2.4 on 2025-09-24 09:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_reimbursement_rejection_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reimbursement',
            name='receipt',
            field=models.FileField(upload_to='receipts/'),
        ),
        migrations.AlterField(
            model_name='reimbursement',
            name='rejection_reason',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.role'),
        ),
    ]
