# Generated by Django 5.2.4 on 2025-09-26 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_reimbursement_receipt_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reimbursement',
        ),
    ]
