# Generated by Django 5.2.4 on 2025-09-29 11:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_discount_expense_fees_expense_tax_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='date',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='fees',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='tax',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='title',
        ),
        migrations.AddField(
            model_name='expense',
            name='account_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='date_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='expense',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='expense',
            name='iban',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='sender_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='sender_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='expense',
            name='transaction_type',
            field=models.CharField(default='Raast Payment', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('transfer', 'Money Transfer'), ('payment', 'Payment'), ('utility', 'Utility Bill'), ('fuel', 'Fuel'), ('medicine', 'Medicine'), ('internet', 'Internet'), ('misc', 'Miscellaneous')], default='misc', max_length=20),
        ),
    ]
