# Generated by Django 5.2.4 on 2025-09-30 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_expense_date_remove_expense_discount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='iban',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='sender_number',
        ),
    ]
