# Generated by Django 5.2.4 on 2025-09-30 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_expense_iban_remove_expense_sender_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='expense',
            name='category',
        ),
    ]
