# Generated by Django 5.2.4 on 2025-09-30 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_remove_expense_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='account_title',
            new_name='receiver_name',
        ),
    ]
