# Generated by Django 5.2.4 on 2025-10-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_account_title_expense_receiver_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gmail',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='gmail_app_password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
